export interface PreAnamneseRequest {
    anamneseID: number,
	alergicoMedicamento: boolean,
	alergicoMedicamentoQual: string,
	usaMedicamento: boolean,
	usaMedicamentoQual: string,
	alergiaAnestesia: boolean,
	alergiaAnestesiaQual: string,
	gravidaOuAmamentando: boolean,
	doencaCardioRespiratoria: boolean,
	doencaCardioRespiratoriaQual: string,
	doencaoTransmissivel: boolean,
	doencaoTransmissivelQual: string,
	diabetico: boolean,
	hipertencaoArterial: boolean,
	hemorragico: boolean,
	cirurgia: boolean,
	cirurgiaQual: string,
	informacaoAdicional: string,

    preAvaliacaoID: number,
	corDentesIncomoda: boolean,
	formatoDentesIncomoda: boolean,
	fumante: boolean,
	umAnoTratamento: boolean,
	escovaDuasVezesDia: boolean,
	usaFioDental: boolean,
	queixa: string

}